### ISSUE TITLE
Error while building libstdc++.spec

### ISSUE THREAD

**Issue by FlarebirdOS** [blackchip-org/lfs-rpm#1] opened 2024-02-21 17:06 UTC
```checking for x86_64-lfs-linux-gnu-strip... x86_64-lfs-linux-gnu-strip
checking for x86_64-lfs-linux-gnu-ranlib... (cached) x86_64-lfs-linux-gnu-ranlib
checking command to parse /usr/bin/nm -B output from x86_64-lfs-linux-gnu-gcc object... failed
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-lfs-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-lfs-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if x86_64-lfs-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if x86_64-lfs-linux-gnu-gcc static flag -static works... no
checking if x86_64-lfs-linux-gnu-gcc supports -c -o file.o... yes
checking if x86_64-lfs-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-lfs-linux-gnu-gcc linker (/lfs/tools/x86_64-lfs-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.```

**Comment by mike-mcgann** [comment] 2024-02-23 15:39
Thank you for reporting this issue. 

I cloned a clean copy of the repository and did not encounter any problems when rebuilding from scratch. I looked around and I found that someone else seems to have run into the same issue:

https://stackoverflow.com/questions/46487529/crosscompiling-gcc-link-tests-are-not-allowed-after-gcc-no-executables-when-che

The top answer recommends adding the `--disable-boostrap` flag. Can you add that and see if you can get the build to work? If it does, I can try adding that on my side. If it works for both of us, that change can be merged in.

**Comment by mike-mcgann** [comment] 2024-03-04 19:36
The repository has been updated with LFS 12.1. Try again and see the newer version resolves the issue that you were seeing.

**Comment by mike-mcgann** [comment] 2024-03-13 03:31
I was unable to reproduce this issue with 12.0 and 12.1. If this issue is still relevant for you, feel free to reopen this ticket and we can work together on solving the problem.

**Closed as completed by mike-mcgann** 2024-03-13 03:31 UTC
